[package]
name = "rill"
version = "0.6.0"
authors = [
    "Denis Kolodin <deniskolodin@gmail.com>",
    "overfloat <rillrate@gmail.com>",
]
edition = "2018"
repository = "https://github.com/rate-technology/rill"
homepage = "https://github.com/rate-technology/rill"
description = "Dynamic logging and tracing system"
categories = ["development-tools::debugging"]
keywords = ["logging"]
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.34"
async-trait = "0.1.42"
derive_more = "0.99.11"
futures = "0.3.8"
log = "0.4.11"
meio = "0.41.0"
meio-connect = "0.41.0"
once_cell = "1.5.2"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.60"
slab = "0.4.2"
thiserror = "1.0.22"
tokio = { version = "0.2.22", features = ["full"] }

[dev-dependencies]
ctrlc = "3.1.7"
env_logger = "0.8.2"
