[server]
address = "0.0.0.0"
meta = true

[export.prometheus]
paths = [
    # updates once only and a snapshot has to be used
    "my.gauge.instances",
    "my.counter.one",
    "my.gauge.multithread",
]

[export.graphite]
paths = [
    "my.counter.two",
]
