[package]
name = "rill-client"
version = "0.24.0"
authors = [
    "Denis Kolodin <deniskolodin@gmail.com>",
    "overfloat <rillrate@gmail.com>",
]
edition = "2018"
repository = "https://github.com/rillrate/rillrate"
homepage = "https://github.com/rillrate/rillrate"
documentation = "https://docs.rs/rillrate/"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["logging"]
categories = ["development-tools::debugging"]
description = "Dynamic logging and tracing system"

[dependencies]
anyhow = "1.0.39"
async-trait = "0.1.48"
derive_more = "0.99.13"
futures = "0.3.13"
log = "0.4.14"
meio = "0.84.2"
meio-connect = "0.84.2"
rill-protocol = { version = "0.24.0", path = "../rill-protocol" }
thiserror = "1.0.24"
typed-slab = "0.1.0"
