[package]
name = "rillrate"
version = "0.30.0-alpha.2"
authors = [
    "Denis Kolodin <deniskolodin@gmail.com>",
    "overfloat <rillrate@gmail.com>",
]
edition = "2018"
repository = "https://github.com/rillrate/rillrate"
homepage = "https://github.com/rillrate/rillrate"
documentation = "https://docs.rs/rillrate/"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["logging"]
categories = ["development-tools::debugging"]
description = "Dynamic logging and tracing system"

[dependencies]
anyhow = "1.0.40"
async-trait = "0.1.50"
derive_more = "0.99.14"
#futures = "0.3.13"
log = "0.4.14"
meio = "0.88.1"
meio-connect = "0.88.1"
once_cell = "1.7.2"
rill-engine = { version = "0.30.0-alpha.2", path = "../rill-engine" }
rill-protocol = { version = "0.30.0-alpha.2", path = "../rill-protocol" }
serde = "1.0.126"
tokio = { version = "1.6.0", features = ["full"] }
#tokio-stream = { version = "0.1.3", features = ["sync"] }
toml = "0.5.8"

[dev-dependencies]
# TODO: Use own interruptor (with a flag)
ctrlc = "3.1.9"
env_logger = "0.8.3"
rand = "0.8.3"
