[package]
name = "rillrate"
version = "0.15.0"
authors = [
    "Denis Kolodin <deniskolodin@gmail.com>",
    "overfloat <rillrate@gmail.com>",
]
edition = "2018"
repository = "https://github.com/rate-technology/rill"
homepage = "https://github.com/rate-technology/rill"
documentation = "https://docs.rs/rillrate/"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["logging"]
categories = ["development-tools::debugging"]
description = "Dynamic logging and tracing system"

[dependencies]
anyhow = "1.0.38"
log = "0.4.13"
rill = { version = "0.15.0", path = "../rill" }
rill-export = { version = "0.15.0", path = "../rill-export" }
rill-protocol = { version = "0.15.0", path = "../rill-protocol" }

[dev-dependencies]
# TODO: Use own interruptor (with a flag)
ctrlc = "3.1.7"
env_logger = "0.8.2"
rand = "0.8.1"
