[package]
name = "rillrate"
version = "0.20.0"
authors = [
    "Denis Kolodin <deniskolodin@gmail.com>",
    "overfloat <rillrate@gmail.com>",
]
edition = "2018"
repository = "https://github.com/rillrate/rillrate"
homepage = "https://github.com/rillrate/rillrate"
documentation = "https://docs.rs/rillrate/"
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["logging"]
categories = ["development-tools::debugging"]
description = "Dynamic logging and tracing system"

[dependencies]
anyhow = "1.0.38"
async-trait = "0.1.42"
#futures = "0.3.13"
log = "0.4.14"
meio = "0.81.0"
rill = { version = "0.20.0", path = "../rill" }
rill-export = { version = "0.20.0", path = "../rill-export" }
rill-protocol = { version = "0.20.0", path = "../rill-protocol" }
serde = "1.0.123"
tokio = { version = "1.2.0", features = ["full"] }
#tokio-stream = { version = "0.1.3", features = ["sync"] }
toml = "0.5.8"

[dev-dependencies]
# TODO: Use own interruptor (with a flag)
ctrlc = "3.1.8"
env_logger = "0.8.3"
rand = "0.8.3"
