[package]
name = "rillrate"
version = "0.12.0"
authors = [
    "Denis Kolodin <deniskolodin@gmail.com>",
    "overfloat <rillrate@gmail.com>",
]
edition = "2018"
repository = "https://github.com/rate-technology/rill"
homepage = "https://github.com/rate-technology/rill"
description = "Dynamic logging and tracing system"
categories = ["development-tools::debugging"]
keywords = ["logging"]
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.38"
rill = { version = "0.12.0", path = "../rill" }
rill-export = { version = "0.12.0", path = "../rill-export" }

[dev-dependencies]
# TODO: Use own interruptor (with a flag)
ctrlc = "3.1.7"
env_logger = "0.8.2"
rand = "0.8.1"
