[package]
name = "rill-export"
version = "0.9.0"
authors = [
    "Denis Kolodin <deniskolodin@gmail.com>",
    "overfloat <rillrate@gmail.com>",
]
edition = "2018"
repository = "https://github.com/rate-technology/rill"
homepage = "https://github.com/rate-technology/rill"
description = "Exporters for rill tracing system"
categories = ["development-tools::debugging"]
keywords = ["logging"]
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.36"
async-trait = "0.1.42"
derive_more = "0.99.11"
log = "0.4.11"
meio = "0.63.0"
meio-connect = "0.63.0"
metacrate = "0.1.1"
mime_guess = "2.0.3"
rill-protocol = { version = "0.9.0", path = "../rill-protocol" }
serde = "1.0.118"
serde-pickle = "0.6.2"
strum = "0.19.5"
strum_macros = "0.19.4"
thiserror = "1.0.22"
tokio = { version = "0.2.22", features = ["full"] }
toml = "0.5.8"
typed-slab = "0.1.0"

[dev-dependencies]
ctrlc = "3.1.7"
env_logger = "0.8.2"
rill = { version = "0.9.0", path = "../rill" }
