[package]
name = "rill-export"
version = "0.6.0"
authors = [
    "Denis Kolodin <deniskolodin@gmail.com>",
    "overfloat <rillrate@gmail.com>",
]
edition = "2018"
repository = "https://github.com/rate-technology/rill"
homepage = "https://github.com/rate-technology/rill"
description = "Exporters for rill tracing system"
categories = ["development-tools::debugging"]
keywords = ["logging"]
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.36"
async-trait = "0.1.42"
log = "0.4.11"
meio = "0.40.0"
meio-connect = "0.40.0"
rill = { version = "0.6.0", path = "../rill" }
strum = "0.19.5"
strum_macros = "0.19.4"
tokio = { version = "0.2.22", features = ["full"] }
