name: Building

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
            components: rustfmt, clippy

      - name: Run cargo build [debug]
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Run cargo build [release]
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
